// Stellar case study design tokens — Bricolage Grotesque + DM Sans + Fraunces + Space Mono
// Scoped to the demo surface (data-demo="stellar"). NOT portfolio shell tokens.
//
// Every value below is a CSS custom property reference, not a raw hex literal.
// The custom properties themselves are declared once, in the
// `[data-demo="stellar"] { ... }` block in StellareatClient.tsx — that block is
// the single source of truth for the hex values. This file just names them.

export const S = {
  color: {
    paper:      'var(--stellar-paper)',
    paper2:     'var(--stellar-paper-2)',
    onFill:     'var(--stellar-on-fill)',
    ink:        'var(--stellar-ink)',
    inkSoft:    'var(--stellar-ink-soft)',
    muted:      'var(--stellar-muted)',
    green:      'var(--stellar-green)',
    greenDeep:  'var(--stellar-green-deep)',
    lime:       'var(--stellar-lime)',
    limeSoft:   'var(--stellar-lime-soft)',
    citrus:     'var(--stellar-citrus)',
    citrusDk:   'var(--stellar-citrus-dark)',
    greenMid:   'var(--stellar-green-mid)',
    greenDark:  'var(--stellar-green-dark)',
    greenStar:  'var(--stellar-green-star)',
    limeMid:    'var(--stellar-lime-mid)',
    inkForest:  'var(--stellar-ink-forest)',
    forest1:    'var(--stellar-forest-1)',
    forest2:    'var(--stellar-forest-2)',
    forest3:    'var(--stellar-forest-3)',
    stickyBg:   'var(--stellar-sticky-bg)',
    stickyInk:  'var(--stellar-sticky-ink)',
  },
  alpha: {
    black06:    'color-mix(in srgb, var(--stellar-black) 6%, transparent)',
    black08:    'color-mix(in srgb, var(--stellar-black) 8%, transparent)',
    black10:    'color-mix(in srgb, var(--stellar-black) 10%, transparent)',
    black12:    'color-mix(in srgb, var(--stellar-black) 12%, transparent)',
    black15:    'color-mix(in srgb, var(--stellar-black) 15%, transparent)',
    white55:    'color-mix(in srgb, var(--stellar-white) 55%, transparent)',
    line:       'color-mix(in srgb, var(--stellar-ink) 10%, transparent)',
    line2:      'color-mix(in srgb, var(--stellar-ink) 6%, transparent)',
    green40:    'color-mix(in srgb, var(--stellar-green) 40%, transparent)',
    green18:    'color-mix(in srgb, var(--stellar-green) 18%, transparent)',
    green20:    'color-mix(in srgb, var(--stellar-green) 20%, transparent)',
    lime40:     'color-mix(in srgb, var(--stellar-lime) 40%, transparent)',
    lime20:     'color-mix(in srgb, var(--stellar-lime) 20%, transparent)',
    citrus10:   'color-mix(in srgb, var(--stellar-citrus) 10%, transparent)',
    ink04:      'color-mix(in srgb, var(--stellar-ink) 4%, transparent)',
    ink06:      'color-mix(in srgb, var(--stellar-ink) 6%, transparent)',
    ink07:      'color-mix(in srgb, var(--stellar-ink) 7%, transparent)',
    ink10:      'color-mix(in srgb, var(--stellar-ink) 10%, transparent)',
    ink12:      'color-mix(in srgb, var(--stellar-ink) 12%, transparent)',
    ink18:      'color-mix(in srgb, var(--stellar-ink) 18%, transparent)',
    ink25:      'color-mix(in srgb, var(--stellar-ink) 25%, transparent)',
    paper66:    'color-mix(in srgb, var(--stellar-paper) 66%, transparent)',
    paper08:    'color-mix(in srgb, var(--stellar-paper) 8%, transparent)',
    paper14:    'color-mix(in srgb, var(--stellar-paper) 14%, transparent)',
    paper60:    'color-mix(in srgb, var(--stellar-paper) 60%, transparent)',
    paper65:    'color-mix(in srgb, var(--stellar-paper) 65%, transparent)',
    paper82:    'color-mix(in srgb, var(--stellar-paper) 82%, transparent)',
    paper38:    'color-mix(in srgb, var(--stellar-paper) 38%, transparent)',
    paper45:    'color-mix(in srgb, var(--stellar-paper) 45%, transparent)',
    // AA-safe caption/disclosure tone — resolves to ~6.7:1 against --stellar-ink,
    // clearing WCAG 2.2 SC 1.4.3's 4.5:1 minimum. Use for any disclosure/fine-print
    // copy on the ink panel; paper45 measures ~4:1 and is too low for body-size text.
    paper68:    'color-mix(in srgb, var(--stellar-paper) 68%, transparent)',
    ink31:      'color-mix(in srgb, var(--stellar-forest-1) 31%, transparent)',
    inkDark10:  'color-mix(in srgb, var(--stellar-ink) 10%, transparent)',
    onFill40:   'color-mix(in srgb, var(--stellar-on-fill) 40%, transparent)',
    onFill08:   'color-mix(in srgb, var(--stellar-on-fill) 8%, transparent)',
    onFill14:   'color-mix(in srgb, var(--stellar-on-fill) 14%, transparent)',
    inkDark08:  'color-mix(in srgb, var(--stellar-ink) 8%, transparent)',
    ink03:      'color-mix(in srgb, var(--stellar-ink) 2.5%, transparent)',
    jcard3dark: 'color-mix(in srgb, var(--stellar-ink) 30%, transparent)',
    shadow:     '0 1px 2px color-mix(in srgb, var(--stellar-ink) 4%, transparent), 0 18px 40px color-mix(in srgb, var(--stellar-ink) 7%, transparent)',
    shadowHov:  '0 24px 50px color-mix(in srgb, var(--stellar-ink) 12%, transparent)',
    shadowFeat: '0 20px 50px color-mix(in srgb, var(--stellar-green-star) 35%, transparent)',
    limeShadow: 'color-mix(in srgb, var(--stellar-green) 40%, transparent)',
  },
  font: {
    display: "'Bricolage Grotesque', sans-serif",
    body:    "'DM Sans', sans-serif",
    italic:  "'Fraunces', serif",
    mono:    "'Space Mono', monospace",
  },
  size: {
    hero:    'clamp(2.4rem,7vw,6rem)',
    display: 'clamp(2.1rem,5.5vw,4rem)',
    title:   'clamp(1.4rem,3vw,2.1rem)',
    body:    'clamp(1.02rem,1.4vw,1.18rem)',
  },
  ease: {
    expo:   'cubic-bezier(.16,1,.3,1)',
    spring: 'cubic-bezier(.34,1.56,.64,1)',
    smooth: 'cubic-bezier(.65,0,.35,1)',
  },
} as const
